ASC.Web/Navigation/LeftNavigationViewComponent.cs
using ASC.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace ASC.Web.Navigation
{
    [ViewComponent(Name = "LeftNavigation")]
    public class LeftNavigationViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(NavigationMenu menu)
        {
            menu.MenuItems = menu.MenuItems.OrderBy(p => p.Sequence).ToList();
            return View(menu);
        }
    }
}

ASC.Web/Views/Shared/_Layout.cshtml
@using Microsoft.Extensions.Options;
@using ASC.Web.Configuration;
@inject IOptions<ApplicationSettings> _configurationSettings;
@{
    Layout = "_MasterLayout";
}
<header>
    <nav class="white" role="navigation">
        <div class="nav-wrapper container">
            <a id="logo-container" href="#" class="brand-logo">
                <img class="responsive-img" src="/images/logo.jpg" alt="logo" />
            </a>
            <ul class="right hide-on-med-and-down">
                <li><a href="/Identity/Account/Login" style="color:black">Login</a></li>
                <li><a href="#" style="color:black">Contact</a></li>
            </ul>
            <ul id="nav-mobile" class="sidenav">
                <li><a href="/Identity/Account/Login">Login</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
            <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        </div>
    </nav>
    <div id="index-banner" class="parallax-container">
        <div class="section no-pad-bot">
            <div class="container">
                <br><br>
                <h1 class="header center teal-text text-lighten-2">Automobile Service Center</h1>
                <div class="row center">
                    <h5 class="header col s12 light">Where Quality meets Safety</h5>
                </div>
                <div class="row center">
                    <a href="http://materializecss.com/getting-started.html" id="downloadbutton" class="btn-large waves-effect waves-light teal lighten-1">Get Started</a>
                </div>
                <br><br>
            </div>
        </div>
        <div class="parallax">
            <img src="/images/background1.jpg" alt="Unsplashed backgroundimg 1">
        </div>
    </div>
    
</header>
<!-- Render Body -->
<main>
    <div class="row margin-bottom-0px">
        <div class="col s12 padding-0px">
            @RenderBody()
        </div>
    </div>
</main>
<!-- Footer -->
<footer class="page-footer teal">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">About Us</h5>
                <p class="grey-text text-lighten-4">
                    Automobile Service Center is certified to perform car services. Our workshop operations started in October 2010.
                    We primarily focus on providing better services to our customers, and as a result of the hard work, we were awarded "Best Service" for 2008.
                </p>
            </div>
            <div class="col l3 s12">
                <h5 class="white-text">Additional Services</h5>
                <ul>
                    <li><a class="white-text" href="#">Services</a></li>
                    <li><a class="white-text" href="#">Finance</a></li>
                    <li><a class="white-text" href="#">Used Cars</a></li>
                    <li><a class="white-text" href="#">Insurance</a></li>
                    <li><a class="white-text" href="#">Driving School</a></li>
                </ul>
            </div>
            <div class="col l3 s12">
                <h5 class="white-text">Connect</h5>
                <ul>
                    <li><a class="white-text" href="#">Facebook</a></li>
                    <li><a class="white-text" href="#">LinkedIn</a></li>
                    <li><a class="white-text" href="#">Twitter</a></li>
                    <li><a class="white-text" href="#">Youtube</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            Powered by <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
        </div>
    </div>
</footer>
@section Scripts {
    @RenderSection("Scripts", required: false)
}

ASC.Web/Views/Shared/_MasterLayout.cshtml
@using Microsoft.Extensions.Options;
@using ASC.Web.Configuration;
@inject IOptions<ApplicationSettings> _configurationSettings
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>@_configurationSettings.Value.ApplicationTitle</title>

    <!-- Fonts and Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Materialize CSS -->
    <link href="~/css/materialize.min.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <!-- DataTables CSS -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css" />
</head>
<body>

    @RenderBody()

    <!-- jQuery (must be first) -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <!-- DataTables -->
    <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>

    <!-- jQuery Validate -->
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.0/jquery.validate.min.js"></script>

    <!-- Materialize JS -->
    <script src="~/js/materialize.min.js"></script>
    <script src="~/js/init.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ASC.Web/Views/Shared/_SecureLayout.cshtml
@using Microsoft.AspNetCore.Http
@using ASC.Utilities
@using ASC.Web.Data
@* Lay thong tin user dang nhap *@
@inject IHttpContextAccessor UserHttpContext
@* Lay menu *@
@inject INavigationCacheOperations navigationCache
@{
    Layout = "_MasterLayout";
    var currentUser = UserHttpContext.HttpContext.User.GetCurrentUserDetails();
}
<!-- Header -->
<header class="secureLayout">
    <nav class="top-nav blue-grey lighten-1">
        <div class="nav-wrapper row valign-wrapper">
            <div class="col s12 valign-wrapper">
                <a href="#" data-target="nav-mobile" class="sidenav-trigger">
                    <i class="material-icons">menu</i>
                </a>
                <h5 class="page-title">Automobile Service Center</h5>
            </div>
        </div>
    </nav>
    <!-- Side NavBar -->
    <!-- Side NavBar -->
    <ul id="nav-mobile" class="sidenav sidenav-fixed">
        <li>
            <div class="user-view">
                <div class="background blue-grey lighten-1"></div>
                <a href="#"><img class="circle" src="~/images/background2.jpg"></a>
                <a href="#"><span class="white-text name">@currentUser.Name</span></a>
                <a href="#"><span class="white-text email">@currentUser.Email</span></a>
            </div>
        </li>
        @await Component.InvokeAsync("LeftNavigation", await navigationCache.GetNavigationCacheAsync())
    </ul>
</header>

<main class="secureLayout">
    <div class="row margin-bottom-8px">
        <div class="col s12">
            @RenderBody()
        </div>
    </div>
    <footer class="page-footer teal">
        <div class="container">
            <div class="row">
                <!-- About Us Section -->
                <div class="col l6 s12">
                    <h5 class="white-text">About Us</h5>
                    <p class="grey-text text-lighten-4">
                        Automobile Service Center is certified to perform car services. Our workshop operations started in October 2010.
                        We primarily focus on providing better services to our customers, and as a result of the hard work, we were awarded "Best Service" for 2008.
                    </p>
                </div>

                <!-- Additional Services Section -->
                <div class="col l3 s12">
                    <h5 class="white-text">Additional Services</h5>
                    <ul>
                        <li><a class="white-text" href="#!">Services</a></li>
                        <li><a class="white-text" href="#!">Finance</a></li>
                        <li><a class="white-text" href="#!">Used Cars</a></li>
                        <li><a class="white-text" href="#!">Insurance</a></li>
                        <li><a class="white-text" href="#!">Driving School</a></li>
                    </ul>
                </div>

                <!-- Connect Section -->
                <div class="col l3 s12">
                    <h5 class="white-text">Connect</h5>
                    <ul>
                        <li><a class="white-text" href="#!">Facebook</a></li>
                        <li><a class="white-text" href="#!">LinkedIn</a></li>
                        <li><a class="white-text" href="#!">Twitter</a></li>
                        <li><a class="white-text" href="#!">Youtube</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Footer Copyright -->
        <div class="footer-copyright">
            <div class="container">
                Powered by
                <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
            </div>
        </div>
    </footer>
</main>

<style>
    .page-footer {
        margin-left: 1000px;
    }
</style>
<form class="hide" method="post" id="logout_form" asp-area="Identity" asp-page="/Account/Logout">
    <input type="submit" value="Logout" />
</form>

<form class="hide" method="post" id="resetPassword_form" asp-area="Identity" asp-page="/Account/InitiateResetPassword">
</form>
@section Scripts {
    <script type="text/javascript">
        $(function () {
            $('#ancrLogout').click(function () {
                $('#logout_form').submit();
            });
            $('#ancrResetPassword').click(function () {
                $('#resetPassword_form').submit();
            });
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.collapsible').collapsible();
        });
    </script>
}
@RenderSection("Scripts", required: false)